### ISSUE TITLE
General Tasks

### ISSUE THREAD

**Issue by caestrella1** [cestrrada/MovieRental#5]
## Tasks
- [x] Create login screen
- [x] Implement admin dashboard functionality
- [x] Finish admin page
- [x] Finalize overall design (cart, add, edit item)
- [x] Add feedback messages for successful item update
~Create order lookup page~ (scrapped)
